export const GET_ERROR = "GET_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const ORDER_HISTORY = "ORDER_HISTORY";

export const STATISTICS = "STATISTICS";
export const GET_RESTAURANT = "GET_RESTAURANT";
export const GET_WISHLIST = "GET_WISHLIST";
export const GET_USER= "GET_USER";
export const GET_WISHLIST_DETAIL = "GET_WISHLIST_DETAIL";
export const ADD_SUCCESS = "ADD_SUCCESS";
export const GET_RESTAURANTDEATAIL ="GET_RESTAURANTDEATAIL"
export const CHANGE_RESTAURANT = "CHANGE_RESTAURANT";